server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.31.39.212:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_name]
        regex: /4evr0-server-app-1
        action: keep
    pipeline_stages:
      - regex:
          expression: '.*event=graph_query func=(?P<func>\S+).*'
      - labels:
          func:
