from enum import Enum


class SkinType(str, Enum):
    DRY = "DRY"
    OILY = "OILY"
    COMBINATION = "COMBINATION"
    SENSITIVE = "SENSITIVE"
    NORMAL = "NORMAL"


class Concern(str, Enum):
    # acne group
    ACNE = "ACNE"
    COMEDONES = "COMEDONES"
    PORE_CONGESTION = "PORE_CONGESTION"
    # oil group
    ENLARGED_PORES = "ENLARGED_PORES"
    OILY_SKIN = "OILY_SKIN"
    # sensitivity group
    SENSITIVE_SKIN = "SENSITIVE_SKIN"
    REDNESS = "REDNESS"
    IRRITATED_SKIN = "IRRITATED_SKIN"
    ATOPIC_PRONE = "ATOPIC_PRONE"
    ROSACEA_PRONE = "ROSACEA_PRONE"
    # dryness group
    DRY_SKIN = "DRY_SKIN"
    DEHYDRATED_SKIN = "DEHYDRATED_SKIN"
    FLAKY_SKIN = "FLAKY_SKIN"
    ROUGH_TEXTURE = "ROUGH_TEXTURE"
    # barrier group
    BARRIER_DAMAGE = "BARRIER_DAMAGE"
    # pigmentation group
    HYPERPIGMENTATION = "HYPERPIGMENTATION"
    DULLNESS = "DULLNESS"
    UNEVEN_SKIN_TONE = "UNEVEN_SKIN_TONE"
    BLEMISHES = "BLEMISHES"
    POST_ACNE_MARKS = "POST_ACNE_MARKS"
    DARK_CIRCLES = "DARK_CIRCLES"
    # protection group
    SUNBURN = "SUNBURN"
    # aging group
    AGING_SIGNS = "AGING_SIGNS"
    WRINKLES = "WRINKLES"
    LOSS_OF_ELASTICITY = "LOSS_OF_ELASTICITY"
    SAGGING_SKIN = "SAGGING_SKIN"


class Effect(str, Enum):
    # calming group
    ANTI_INFLAMMATORY = "ANTI_INFLAMMATORY"
    SOOTHING = "SOOTHING"
    # barrier group
    BARRIER_REPAIR = "BARRIER_REPAIR"
    # hydration group
    HYDRATING = "HYDRATING"
    MOISTURE_RETENTION = "MOISTURE_RETENTION"
    # acne_oil group
    SEBUM_REGULATION = "SEBUM_REGULATION"
    ANTIMICROBIAL = "ANTIMICROBIAL"
    PORE_MINIMIZING = "PORE_MINIMIZING"
    # acne_exfoliation group
    KERATOLYTIC = "KERATOLYTIC"
    COMEDOLYTIC = "COMEDOLYTIC"
    EXFOLIATING = "EXFOLIATING"
    # repair group
    SMOOTHING = "SMOOTHING"
    WOUND_HEALING = "WOUND_HEALING"
    # pigmentation group
    DEPIGMENTING = "DEPIGMENTING"
    BRIGHTENING = "BRIGHTENING"
    # protection group
    ANTIOXIDANT = "ANTIOXIDANT"
    PHOTOPROTECTIVE = "PHOTOPROTECTIVE"
    # aging group
    ANTI_AGING = "ANTI_AGING"
    FIRMING = "FIRMING"


class Constraint(str, Enum):
    FRAGRANCE_FREE = "FRAGRANCE_FREE"
    ALCOHOL_FREE = "ALCOHOL_FREE"
    VEGAN = "VEGAN"
    HYPOALLERGENIC = "HYPOALLERGENIC"
    EWG_GREEN = "EWG_GREEN"
